---
- name: Django | Packages | Install required system packages.
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - git
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libxml2-dev
    - libxslt1-dev
    - libjpeg-dev
    - libfreetype6-dev
    - zlib1g-dev
    - libpng12-dev

- name: Django | Pip | Install Requirements.
  pip: requirements="{{django.requirements}}"
