# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.ssh.insert_key = false

    # open coesione web, postgres, redis, solr
    config.vm.define "oc" do |oc_config|

        oc_config.vm.synced_folder "../", "/vagrant"
        oc_config.vm.box = "ubuntu/trusty64"
        oc_config.vm.hostname = "oc"
        oc_config.vm.network :private_network, ip: "192.168.111.101"
        oc_config.vm.network "forwarded_port", guest: 8000, host: 8000
        oc_config.vm.network "forwarded_port", guest: 8983, host: 8983

        oc_config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
        oc_config.vm.network :forwarded_port, guest: 22, host: 2201

        # default provider set to virtualbox
        oc_config.vm.provider "virtualbox"
        oc_config.vm.provider "vmware_fusion"

        # virtualbox definitions
        oc_config.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", 2048]
          vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end

    end

    # tilestache server
    config.vm.define "ts" do |ts_config|
        ts_config.vm.synced_folder "../", "/vagrant"
        ts_config.vm.box = "ubuntu/trusty64"
        ts_config.vm.hostname = "ts"
        ts_config.vm.network :private_network, ip: "192.168.111.102"
        ts_config.vm.network "forwarded_port", guest: 8009, host: 8009

        ts_config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
        ts_config.vm.network :forwarded_port, guest: 22, host: 2202

        # default provider set to virtualbox
        ts_config.vm.provider "virtualbox"
        ts_config.vm.provider "vmware_fusion"

        # virtualbox definitions
        ts_config.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", 528]
          vb.customize ["modifyvm", :id, "--cpus", 2]
          vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
    end

end
