# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.ssh.insert_key = false
    config.vm.synced_folder "../", "/vagrant"
    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "oc"
    config.vm.network :private_network, ip: "192.168.111.101"
    config.vm.network "forwarded_port", guest: 80, host: 8000
    config.vm.network "forwarded_port", guest: 8983, host: 8983

    # default provider set to virtualbox
    config.vm.provider "virtualbox"
    config.vm.provider "vmware_fusion"

    # virtualbox definitions
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

end
